# Generated by Django 5.1 on 2024-09-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_role_permissions_loginhistory_login_ip_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
