# Generated by Django 5.1 on 2024-09-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_loginhistory_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', null=True),
        ),
    ]
